name: 'fullstory_demo_package'
version: '0.1.1'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:        
  - "target"
  - "dbt_packages"


models:
  fullstory_demo_package:
    example:
      materialized: view
